'use strict';

// Nostalgia Rewind catalog configuration.
// Catalogs are built from factual media tags rather than catalog-specific tags.
// Toggle a catalog by changing only its enabled value.

const SORT_MODES = ['featured', 'alphabetical', 'chronological'];
const MEDIA_TYPES = ['series', 'movie'];
const MATCH_MODES = ['all', 'tag', 'tags-any'];

const KNOWN_TAGS = [
  '2000s',
  '2000s-anime',
  '2000s-kids',
  '90s',
  '90s-action',
  '90s-anime',
  '90s-classics',
  '90s-comedy',
  '90s-kids',
  'action',
  'action-anime',
  'adult-animation',
  'adult-swim',
  'after-school',
  'animated-movies',
  'anime',
  'anime-movies',
  'cartoon-network',
  'cartoon-network-movies',
  'comedy',
  'comedy-movies',
  'cult-animation',
  'dc',
  'disney-afternoon',
  'disney-channel',
  'disney-channel-movies',
  'disney-movies',
  'early-2000s',
  'early-2000s-classics',
  'early-90s',
  'educational',
  'educational-nostalgia',
  'family-movies',
  'fantasy-adventure-movies',
  'fantasy-anime',
  'forgotten-obscure',
  'fox-kids',
  'kids-animation',
  'kids-teen-sitcoms',
  'kids-wb',
  'late-90s',
  'live-action-kids',
  'marvel',
  'mid-90s',
  'nickelodeon',
  'nickelodeon-gas',
  'nickelodeon-movies',
  'nicktoons',
  'one-saturday-morning',
  'pbs',
  'pbs-kids',
  'playhouse-disney',
  'preschool',
  'preschool-nostalgia',
  'retro-syndication',
  'saturday-morning',
  'science-nature',
  'snick',
  'spooky-movies',
  'superhero-animation',
  'superhero-movies',
  'syndicated-classics',
  'teen-movies',
  'toon-disney',
  'toonami',
  'weird-cartoons',
];

const catalogs = [
  {
    id: 'nostalgia-rewind-tv',
    name: 'Nostalgia Rewind TV',
    type: 'series',
    match: 'all',
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-nickelodeon',
    name: 'Nickelodeon',
    type: 'series',
    match: 'tags-any',
    tags: ['nickelodeon', 'nicktoons', 'snick', 'nickelodeon-gas'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-cartoon-network',
    name: 'Cartoon Network',
    type: 'series',
    match: 'tags-any',
    tags: ['cartoon-network'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-disney-tv',
    name: 'Disney TV',
    type: 'series',
    match: 'tags-any',
    tags: [
      'disney-channel',
      'toon-disney',
      'disney-afternoon',
      'one-saturday-morning',
      'playhouse-disney',
    ],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-saturday-after-school',
    name: 'Saturday Morning & After School',
    type: 'series',
    match: 'tags-any',
    tags: [
      'saturday-morning',
      'after-school',
      'fox-kids',
      'kids-wb',
      'syndicated-classics',
      'retro-syndication',
    ],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-pbs-preschool',
    name: 'PBS & Preschool',
    type: 'series',
    match: 'tags-any',
    tags: ['pbs', 'pbs-kids', 'preschool', 'educational', 'science-nature'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-anime',
    name: 'Anime',
    type: 'series',
    match: 'tags-any',
    tags: ['anime', 'fantasy-anime'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-live-action-sitcoms',
    name: 'Live Action & Sitcoms',
    type: 'series',
    match: 'tags-any',
    tags: ['live-action-kids', 'kids-teen-sitcoms'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-adult-animation',
    name: 'Adult Animation',
    type: 'series',
    match: 'tags-any',
    tags: ['adult-animation', 'adult-swim'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-forgotten-obscure',
    name: 'Forgotten & Obscure',
    type: 'series',
    match: 'tags-any',
    tags: ['forgotten-obscure'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-movies',
    name: 'Nostalgia Rewind Movies',
    type: 'movie',
    match: 'all',
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-kids-family-movies',
    name: 'Kids & Family Movies',
    type: 'movie',
    match: 'tags-any',
    tags: ['family-movies', 'animated-movies'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-tv-movies-specials',
    name: 'TV Movies & Specials',
    type: 'movie',
    match: 'tags-any',
    tags: ['disney-channel-movies', 'nickelodeon-movies', 'cartoon-network-movies'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-anime-superhero-movies',
    name: 'Anime & Superhero Movies',
    type: 'movie',
    match: 'tags-any',
    tags: ['anime-movies', 'superhero-movies'],
    sort: 'alphabetical',
    enabled: true,
  },
  {
    id: 'nostalgia-rewind-teen-comedy-adventure',
    name: 'Teen, Comedy & Adventure',
    type: 'movie',
    match: 'tags-any',
    tags: ['teen-movies', 'comedy-movies', 'fantasy-adventure-movies', 'spooky-movies'],
    excludeTags: ['family-movies'],
    sort: 'alphabetical',
    enabled: true,
  },
];

module.exports = {
  catalogs,
  KNOWN_TAGS,
  SORT_MODES,
  MEDIA_TYPES,
  MATCH_MODES,
};
